// Full text of the NavDirect Pty Ltd Terms and Conditions, structured for rendering.
// Source of truth: NavDirect_ONEPOINTTerms_and_Conditions.pdf (public/terms-and-conditions.pdf
// is the exact same document, offered as a download alongside this on-page rendering).
//
// Each section has a `title` and a `body` array. Body items are either:
//   { type: 'p', text }                              — a paragraph
//   { type: 'sub', text }                             — a bold sub-heading within a section
//   { type: 'list', ordered, items }                  — items: string | { text, sublist: { ordered, items } }
//   { type: 'definitions', items: [{ term, text }] }  — the defined-terms list in clause 1.1

export const termsAndConditionsContent = [
  {
    title: '1. Definitions and Interpretation',
    body: [
      { type: 'sub', text: '1.1 Definitions' },
      { type: 'p', text: 'The following definitions apply in this Agreement unless the context requires otherwise:' },
      {
        type: 'definitions',
        items: [
          { term: 'Agreement', text: 'means this Agreement which consists of the Proposal, these Terms and Conditions and any other annexures, schedules or documents attached to this Agreement.' },
          { term: 'Approvals', text: 'means all approvals, authorisations, permits, consents, determinations and licences which are issued, or required to be issued, by any Governmental Agency to permit the full and proper performance of the Company’s obligations under this Agreement.' },
          { term: 'Business Day', text: 'means a day (other than a Saturday, Sunday or public holiday) when banks in Sydney, New South Wales are open for business.' },
          { term: 'Change of Control', text: 'means, in respect of a particular entity, a person who Controls that entity ceasing to do so or another person acquiring Control of it.' },
          { term: 'Claims', text: 'means any claims including actions, complaints, debts, demands, dues, proceedings, suits or other legal recourse (whether in contract or tort (including negligence), at law or in equity or under any Legislation) and including any causes of action or rights to bring or make any such claim.' },
          { term: 'Commencement Date', text: 'means the date that this Agreement is deemed to have been accepted by the Client and will become binding as between the Company and the Client in accordance with Clause 2.4.' },
          {
            term: 'Confidential Information',
            text: 'means all information relating to a party, any customer, clients, suppliers, distributors or joint venture partners, of the party and/or any of the business or financial affairs of any of them, including:',
            sublist: {
              ordered: false,
              items: [
                'any information that is specifically designated by any of them as confidential;',
                'any information which, by its nature, may reasonably be regarded as confidential;',
                {
                  text: 'any information relating to any:',
                  sublist: {
                    ordered: true,
                    items: [
                      'agreements, arrangements or terms of trade with any existing or prospective customers, clients, suppliers, distributors or joint venture partners or other contractual counterparties;',
                      'customers, clients, suppliers, distributors, joint venture partners, employees, technologies, products, services, proposals, market opportunities, business or product development plans, pricing, financial position or performance, capabilities, capacities, operations or processes; or',
                      'Intellectual Property Rights, of any of them; and',
                    ],
                  },
                },
                'any note, calculation, conclusion, summary or other material derived or produced partly or wholly from any such information;',
                'negotiations in relation to, and the terms of, this Agreement, whether that information is visual, oral, documentary, electronic, machine-readable tangible, intangible or any other form, relating to the Company or any Related Entity of the Company including but not limited to any specifications, formulae, know how, concepts, inventions, ideas, software, designs, copyright, trade secrets or any information relating to any business, products, markets, operations, processes, techniques, technology, forecasts, strategies or any other matter.',
              ],
            },
          },
          { term: 'Consequential Loss', text: 'means any indirect, special, punitive, exemplary or consequential Loss, including loss of profits or revenue, loss of goodwill or reputation, business interruption, loss of data and failure to realise any anticipated savings or benefits of any kind.' },
          { term: 'Control', text: 'includes the meaning given in Section 50AA of the Corporations Act.' },
          { term: 'Copyright Act', text: 'means the Copyright Act 1968 (Cth).' },
          { term: 'Corporations Act', text: 'means the Corporations Act 2001 (Cth).' },
          { term: 'Costs', text: 'means Fees and Disbursements.' },
          { term: 'Default Rate', text: 'means, in respect of any particular invoice, a rate of interest equal to 10.00%.' },
          {
            term: 'Disbursements',
            text: 'means any and all reasonable out-of-pocket expenses, charges or other costs that we pay or incur on your behalf in connection with the Services, including:',
            sublist: {
              ordered: false,
              items: [
                'printing and photocopying costs, word-processing charges, postage and express delivery charges, telephone call and facsimile transmission charges, courier services fees, costs of printed proofs, costs of photography and costs of media productions;',
                'taxes and any other similar transaction or registration charges, including any interest, fine or penalty in respect thereof; and',
                'Third Party Fees.',
              ],
            },
          },
          {
            term: 'Event of Default',
            text: 'means any of the following on the part of a party:',
            sublist: {
              ordered: false,
              items: [
                'committing any material or persistent breach of this Agreement;',
                'repudiating or, or, in the reasonable opinion of the Company, evincing an intention to repudiate, this Agreement;',
                'if the Client is a company, undergoing a Change of Control without the prior written consent of the Company;',
                'misleading the Company in any material way; and/or',
                'an Insolvency Event occurring in respect of the Client.',
              ],
            },
          },
          { term: 'Fees', text: 'means our professional fees for our provision of the Services to you under this Agreement calculated in accordance with clause 9.' },
          { term: 'Governmental Agency', text: 'means any government or governmental, semi-governmental, administrative, fiscal or judicial body, department, commission, authority, tribunal, agency or entity whether foreign, supranational, federal, state, territorial or local.' },
          { term: 'GST', text: 'has the same meaning given to that expression in the GST Law.' },
          { term: 'GST Act', text: 'means A New Tax System (Goods and Services Tax) Act 1999 (Cth), as in force from time to time.' },
          { term: 'GST Law', text: 'has the same meaning given to that expression in the GST Act.' },
          {
            term: 'Insolvency Event',
            text: 'means, in respect of a party any of the following events or any analogous event:',
            sublist: {
              ordered: false,
              items: [
                'where the party is an individual, that party commits an act of bankruptcy or is declared bankrupt or insolvent or that party’s estate otherwise becomes liable to be dealt with under any law relating to bankruptcy or insolvency;',
                'where the party is a company, a resolution is passed or court order made for the winding up of that party or an administrator is appointed to that party pursuant to any relevant law;',
                'a receiver or manager or receiver and manager is appointed to the assets or undertaking of the party or any part thereof; or',
                'the party is otherwise unable to pay its debts as and when they fall due.',
              ],
            },
          },
          { term: 'Intellectual Property Rights', text: 'means patents, rights to inventions, copyright and related rights, moral rights, trademarks and service marks, trade names and domain names, rights in get-up, rights to goodwill or to sue for passing off or unfair competition, rights in designs, rights in computer software, database rights, rights in confidential information (including know-how, trade secrets and marketing secrets) and any other intellectual property rights, in each case whether registered or unregistered and including all applications (or rights to apply) for, and renewals or extensions of, such rights and all similar or equivalent rights or forms of protection which subsist or will subsist now or in the future in any part of the world.' },
          { term: 'Legislation', text: 'means any statute, legislation, proclamation, rule, code, regulation, ordinance, constitutional provision, treaty, decree, convention or by-law.' },
          { term: 'Liability Cap', text: 'has the meaning given in clause 11.5(a).' },
          {
            term: 'Loss',
            text: 'means any loss, damage, debt, cost, charge, expense, fine, outgoing, penalty, diminution in value, deficiency or other liability of any kind or character that a party pays, suffers or incurs or is liable for, including any:',
            sublist: {
              ordered: false,
              items: [
                'liabilities on account of any taxation of any kind, including indirect taxation;',
                'interest, penalties and other amounts payable to third parties;',
                'legal and other professional fees and expenses (on a full indemnity basis) and other costs incurred in connection with investigating, defending or settling any Claim, whether or not resulting in any liability; and',
                'amounts paid in settlement of any Claim, and includes any Consequential Loss.',
              ],
            },
          },
          { term: 'Moral Rights', text: 'has the same meaning as that term has in Part IX of the Copyright Act.' },
          {
            term: 'Out-of-Scope Services',
            text: 'means:',
            sublist: {
              ordered: false,
              items: [
                'any services that do not fall wholly within the scope of the Services set out in the Proposal; or',
                'any work and/or services hours in excess of the total approved hours of marketing services per month as set out in the Proposal; or',
                'any financial, investment, taxation or legal advice and/or services.',
              ],
            },
          },
          { term: 'Privacy Act', text: 'means the Privacy Act 1988 (Cth).' },
          { term: 'The Proposal', text: 'means the document headed “Proposal” or “Proposals” or similar, setting out the scope of the Services for this Agreement, estimate of costs, budget and the number of hours of marketing services per month, as provided by the Company to or is accessible by the Client, and accepted by the parties in accordance with this Agreement and/or approved by the Client.' },
          {
            term: 'Related Entity',
            text: 'means, in respect of a party means:',
            sublist: {
              ordered: false,
              items: [
                'any person under the Control of that party, any person that Controls that party, and any person under the Control of any of them;',
                'A holding company of that party;',
                'A subsidiary of that party;',
                'A subsidiary of a holding company of that party;',
                'Any entity that is Controlled by that party;',
                'Any entity that Controls that party;',
                'Any entity that is under common Control with that party;',
                'Any entity that has at least one common majority shareholder and/or director with that party;',
                'Any entity that is a related body corporate of that party as defined in the Corporations Act 2001 (Cth);',
                'any trust which that party is a trustee or a beneficiary.',
              ],
            },
          },
          { term: 'Relevant IP', text: 'means all Intellectual Property Rights that the Company makes, develops or conceives (whether alone or in conjunction with someone else) in the course of, or arising out of, the Services, and all other Intellectual Property Rights of the Company that the Company uses in the course of providing the Services.' },
          { term: 'Representatives', text: 'means, in respect of a person, its employees, consultants, agents and advisors and, in respect of a body corporate, includes its officers.' },
          { term: 'Services', text: 'means the services that the Company will provide under this Agreement in accordance with clause 3.1, as set out under the Proposal.' },
          { term: 'Standard Hourly Rates', text: 'means $150.00 per hour plus GST or as revised from time to time in accordance with clause 9.7, whichever is higher.' },
          { term: 'Third Party Fees', text: 'means any and all fees, charges or other costs of any Third Party Service Providers.' },
          { term: 'Third Party Payer', text: 'means any person, other than the Client, that has agreed or undertaken, or agrees or undertakes, to pay all or any part of the Costs on behalf of the Client.' },
          { term: 'Third Party Service Providers', text: 'means any third parties that may need to be engaged on your behalf in connection with the Services.' },
          { term: '“we”, “us” or “the Company”', text: 'means NavMedia Pty Ltd trading as “OnePoint” (ABN 50 165 893 309).' },
          { term: 'Works', text: 'means all programs and programming and literary, dramatic, musical and artistic works within the meaning of the Copyright Act.' },
          {
            term: 'Working Files',
            text: 'means any documents, records, or data compilations, whether in physical or electronic form, that are used by the Company to deliver the Services to the Client, including but are not limited to:',
            sublist: {
              ordered: false,
              items: [
                'any draft versions of any deliverables, work, products and services created, made or delivered pursuant to this Agreement;',
                'any project files, including project plans, timelines, budgets, designs, fonts and raw artwork, procedures, methodology used in the provision of the Services under this Agreement;',
                'operational data, including schedules, meeting notes, file notes and task lists; and',
                'correspondence, including emails, letters and other forms of communications which are related to this Agreement.',
              ],
            },
          },
          { term: '“you” or the “Client”', text: 'means the party described in the Proposal under the heading “Customer Details”.' },
        ],
      },
      { type: 'sub', text: '1.2 Interpretation' },
      { type: 'p', text: 'The following rules of interpretation apply in this Agreement unless the context requires otherwise:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'headings in this Agreement are for convenience only and do not affect its interpretation or construction;',
          'no rule of construction applies to the disadvantage of a party because this Agreement is prepared by, or on behalf of, that party;',
          'where any word or phrase is defined, any other part of speech or other grammatical form of that word or phrase has a cognate meaning;',
          'a reference to a document (including this Agreement) is a reference to that document (including any schedules and annexures) as amended, consolidated, supplemented, novated or replaced;',
          'references to recitals, clauses, subclauses, paragraphs, annexures, schedules and parts are references to recitals, clauses, subclauses, paragraphs, annexures, schedules and parts of or to this Agreement;',
          {
            text: 'a reference to any Legislation includes:',
            sublist: {
              ordered: true,
              items: [
                'that Legislation as amended, extended, consolidated, modified or applied by or under any other Legislation, whether before or after execution of this Agreement;',
                'any Legislation which that Legislation re-enacts, whether with or without modification; and',
                'any subordinate Legislation made, whether before or after execution of this Agreement, under that Legislation (including as amended, extended, consolidated, modified or applied) or any Legislation which that subordinate Legislation re-enacts;',
              ],
            },
          },
          {
            text: 'a reference to any law: (i) includes a reference to any Legislation, judgment, rule of common law or equity or rule of any applicable stock exchange; and (ii) is a reference to that law as amended, consolidated, supplemented or replaced, and any other law made under it;',
          },
          'an expression importing a natural person includes any individual, corporation or other body corporate, partnership, trust or association and any Governmental Agency and that person’s personal representatives, successors, permitted assigns, substitutes, executors and administrators;',
          'a reference to writing includes any communication sent by post, facsimile or email; a reference to time refers to time in Sydney, New South Wales and time is of the essence; a reference to any Costs, including Fees and Disbursements, includes any interest owing thereon under clauses 13 and 10.14;',
          'all monetary amounts are in Australian currency;',
          'the word “month” means calendar month and the word “year” means 12 calendar months;',
          'a reference to the “date of this Agreement” is a reference to the date on which this Agreement becomes binding in accordance with clause 2.4;',
          'the meaning of general words is not limited by specific examples introduced by “include”, “includes”, “including”, “for example”, “in particular”, “such as” or similar expressions;',
          'a reference to a “party” is a reference to a party to this Agreement and if more than one, the reference shall include any one or combination of them and this Agreement shall bind them jointly and each of them severally;',
          'a reference to a “third party” is a reference to a person that is not a party to this Agreement;',
          'a reference to a liability includes a present, prospective, future or contingent liability;',
          'a reference to any thing is a reference to the whole and each part of it;',
          'a reference to a group of persons is a reference to all of them collectively and to each of them individually;',
          'words in the singular include the plural and vice versa; and',
          'a reference to one gender includes a reference to the other genders.',
        ],
      },
    ],
  },
  {
    title: '2. Engagement',
    body: [
      { type: 'p', text: '2.1 The Client hereby engages the Company to provide, and the Company hereby agrees to provide, the Services to the Client on the terms of this Agreement.' },
      { type: 'sub', text: 'Non exclusivity' },
      { type: 'p', text: '2.2 Subject to the Client’s obligations under this Agreement, the Client may at any time engage any third party, or use any member of the Client’s staff, to provide goods and/or services similar or identical to the Services.' },
      { type: 'p', text: '2.3 Subject to the Company’s obligations under this Agreement, the Company may provide services similar to the Services to any other person during the term.' },
      { type: 'sub', text: 'Offer and acceptance' },
      { type: 'p', text: '2.4 The provision of a copy of this Agreement to the Client constitutes an offer by the Company to provide the Services to the Client on the terms of this Agreement. This Agreement will be deemed to have been accepted and will become binding as between the Company and the Client upon the earliest to occur of the Client:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'duly executing a copy of this Agreement and returning it to us;',
          'otherwise communicating to us, whether in writing or verbally, its acceptance of that offer, including communication of acceptance using the Company’s online platform; and',
          'giving us any instructions in connection with the Services after having received a copy of this Agreement.',
        ],
      },
      { type: 'sub', text: 'Nature of relationship' },
      { type: 'p', text: '2.5 The Company is an independent contractor of the Client and nothing in this Agreement form a relationship of employer and employee, principal and agent, partnership or joint venture between the parties. The Company does not have, and will not hold themselves out as having, any authority to bind the Client in any matter including but not limited to any contracts, commitments, expenses, liabilities or obligations of any nature.' },
      { type: 'sub', text: 'Authorisations' },
      { type: 'p', text: '2.6 The Company represents and warrants to the Client, and the Client represents and warrants to the Company, that it has taken all necessary actions, and obtained all required Authorisations, to enable it to execute, deliver and perform its obligations under this Agreement, and any such Authorisations are in full force and effect.' },
    ],
  },
  {
    title: '3. Services',
    body: [
      { type: 'p', text: '3.1 Subject to clause 3.2, the scope of the Services is limited to:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'the services described in the quote attached to this Agreement; or',
          'the services described in the Proposal; and',
          'the number of hours per month specified in the Proposal; and',
          'specifically excludes all Out-of-Scope Services.',
        ],
      },
      { type: 'p', text: '3.2 Unless stated otherwise in this Agreement, the Company shall provide the Client with up to two revisions of an initial concept free of charge following the presentation of the initial concept. Any additional revisions shall be considered as Out-of-Scope Services and shall incur additional Costs calculated on the basis of the time spent by us in providing the Client with such additional revisions at our Standard Hourly Rates.' },
      { type: 'p', text: '3.3 Unless stated otherwise in this Agreement, the Client may request a suspension of the Services described in the Proposal, once in every 12 months period, for a period of up to 14 days (Suspension Period), provided that there is no existing breach of this Agreement by the Client at the time of such request. The Company shall not provide any of the Services under this Agreement to or on behalf of the Client during the Suspension Period and the Client’s tax invoice for the month of the Suspension Period shall be reduced by the percentage calculated using the formulae below:' },
      { type: 'p', text: 'R = (DOS × 100%) / DOM — where R = percentage of reduction, DOS = the number of days of the Suspension Period, DOM = the number of days in the month of the Suspension Period.' },
      { type: 'p', text: 'E.g.: if the Client requests a suspension of 7 days period during the month of January, the Client’s tax invoice for the month of January shall be reduced by 22.60% ((7 days / 31 days) x 100%)' },
      { type: 'p', text: '3.4 The scope of the Services and the Out-of-Scope Services:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'may be varied at any time by agreement in writing between the parties; and',
          'will not be taken to have been varied without such agreement.',
        ],
      },
      { type: 'p', text: '3.5 The Client acknowledges that additional Costs may be payable as a result of any variation to the Services or the Out-of-Scope Services pursuant to Clause 3.4 and hereby agrees to pay such additional Costs in accordance with the terms of this Agreement.' },
      { type: 'sub', text: 'Your cooperation' },
      { type: 'p', text: '3.6 To perform the Services successfully, we require your timely co-operation. Accordingly, you must:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'provide in a timely fashion all information, documents and instructions that we reasonably require to enable us to provide the Services;',
          'at all times tell us openly and honestly everything relevant to the Services;',
          'arrange access to third parties where applicable;',
          'make senior executives available for consultation on request where applicable; and',
          'make decisions promptly to facilitate the performance of the Services.',
        ],
      },
      { type: 'sub', text: 'Information that you give us' },
      { type: 'p', text: '3.7 Our work will be based on the documentation and information that you provide to us and any documentation and information that third parties provide to us on your behalf. We rely on you to bring to our attention any changes in such documentation and information as originally presented, as it may affect the performance of our services. We will not verify the accuracy or completeness of any such documentation or information. You hereby represent and warrant to us that, to the best of your knowledge and belief, all such documentation and information is and will be:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'complete, true and accurate in all material respects; and',
          'not misleading in any material respect, nor rendered misleading in any material respect by any failure to disclose any other information.',
        ],
      },
      { type: 'sub', text: 'Timetable' },
      { type: 'p', text: '3.8 Unless expressly agreed otherwise in writing between the Company and the Client, dates in any timetable for the provision of the Services are intended for planning and estimating purposes only and are not contractually binding. The timely completion of the Services requires your co-operation in accordance with clause 3.6. Estimates of time for completion of the Services are given on the assumption that we receive this co-operation. Any default or delay in providing this co-operation may result in additional Costs.' },
      { type: 'sub', text: 'Obligations owed to the Client only' },
      { type: 'p', text: '3.9 Unless expressly agreed otherwise in writing between the Company and the Client:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'the Services will be provided solely for the benefit and use of the Client and we accept no liability or responsibility to any third party in respect of the Services; and',
          'our engagement to provide the Services for the Client pursuant to this Agreement does not extend to include services for any Related Entities of the Client, or any Representatives of the Client or of any such Related Entities, or Third Party Payers, and we take on no responsibilities, obligations or duties to any such third parties, and no fiduciary relationship exists between us and any such third parties.',
        ],
      },
      { type: 'p', text: '3.10 Except as required by law, you must not provide any documentation or deliverables in respect of the Services to any third party (including the filing of information containing or referring to any of our reports with regulators or the inclusion of our reports in any public document) without our prior written consent.' },
    ],
  },
  {
    title: '4. Client-Supplied Contents',
    body: [
      { type: 'p', text: '4.1 The Client must provide to the Company all contents (including all of the text, graphics, designs, software, data, sound and video files) which are necessary for the Company to provide the Services to the Client (the Client-Supplied Contents) in the forms and formats as directed by the Company. The Client hereby agrees to pay any additional Costs to the Company in the event that the Client fails to provide any necessary contents to the Company or provide contents in the forms and formats as directed by the Company.' },
      { type: 'p', text: '4.2 The Client hereby represents and warrants that the Client-Supplied Contents:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'do not infringe any copyright or other legal right of any other person;',
          'do not infringing upon or violating any copyright, trademark, patent or other intellectual property or proprietary right;',
          'do not breach of any duty of confidentiality by which you are bound, whether by way of a fiduciary or contractual relationship;',
          'do not breach of any person’s privacy or publicity rights;',
          'do not misrepresent any facts, including the impersonation of any person or entity or a misrepresentation of an affiliation with any person or entity (including any sponsorship or endorsement);',
          'do not violate any applicable law, statute, ordinance or regulation, or encouraging of others to do so;',
          'if they contain images of minors, the Client has obtained all necessary permissions, authority and consents to use such images from the appropriate parties, including but are not limited to government authorities, parents and guardians.',
        ],
      },
      { type: 'p', text: '4.3 Without limiting the generality of Clause 11.2 below, the Client irrevocably indemnifies, releases and covenants to hold the Company harmless from and against all Claims and Losses that may be suffered by, taken or made against the Company which arise in connection with the Client’s breach of it warranties under Clause 4.2.' },
    ],
  },
  {
    title: '5. Subcontractors and Non-Solicitation',
    body: [
      { type: 'p', text: '5.1 We reserve the right to engage subcontractors and any reference in this Agreement to our staff includes subcontractor staff. Unless you expressly agree otherwise, we will remain responsible to you for any of the Services that are provided by our subcontractors.' },
      { type: 'sub', text: 'Non-solicitation' },
      { type: 'p', text: '5.2 For the duration of this Agreement and for a period of 12 months after the earlier of the termination of this Agreement and the completion of the Services, you must not, without our prior written consent, employ, or procure any third party to employ, any employee of ours and/or our Related Entity who has taken part in the performance of the Services.' },
      { type: 'p', text: '5.3 For each breach of Clause 5.2 of this Agreement, the Client must pay to the Company (or to our Related Entity if the breach relates to an employee of our Related Entity) as liquidated damages, a sum equivalent to 50% of the annual salary of each employee of the Company and/or our Related Entity, employed by Client or procured by a third party in breach of Clause 5.2. The parties agree that the amount specified under this Clause is a genuine pre-estimation of the loss that the Company and/or the Company’s Related Entity would suffer as a result of such breach by the Client and that such amount is reasonable and proportionate to the anticipated and actual harm caused by the breach, and is not intended to operate as a penalty.' },
    ],
  },
  {
    title: '6. Communications Protocol',
    body: [
      { type: 'sub', text: 'Instructions' },
      { type: 'p', text: '6.1 We will accept instructions in connection with the Services from anyone who, in our reasonable opinion, has apparent authority to give us such instructions on your behalf, including any of the persons named in the Proposal under the section “Customer Details”. Any changes to the persons named as having such authority must be agreed in writing between the parties.' },
      { type: 'sub', text: 'Progress reports' },
      { type: 'p', text: '6.2 You may request, at any time, a report of the progress of our Services. We reserve the right to charge for the provision of progress reports.' },
      { type: 'sub', text: 'Electronic communications' },
      { type: 'p', text: '6.3 We may communicate with you electronically. Information transmitted electronically cannot be guaranteed to be private or free of viruses or errors and consequently such information could arrive late or be intercepted, corrupted, lost, destroyed or incomplete or otherwise be adversely affected or unsafe to use. We will use commercially reasonable procedures to check for viruses before sending information electronically, but we will not be liable to you in respect of any error or omission, or loss of confidentiality, arising from or in connection with the electronic communication of information to you. You hereby consent to our communicating with you electronically and to our exchange of electronic communications, including confidential documents, via unencrypted means. If you do not accept these risks, you must promptly notify us in writing that you do not want us to communicate electronically with you.' },
      { type: 'sub', text: 'Privacy' },
      { type: 'p', text: '6.4 You must only disclose personal information to us if:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'doing so is necessary for us to perform the Services; and',
          'such disclosure will not infringe the protections afforded to any person by the Privacy Act.',
        ],
      },
      { type: 'p', text: '6.5 We will collect personal information from you in the course of providing our Services. We may also obtain personal information from third party searches, other investigations and, sometimes, from adverse parties. If personal information (within the meaning of the Privacy Act) is disclosed to us in the course of our provision of the Services:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'we will treat it in accordance with our legal obligations; and',
          'if disclosed to us by a third party, it will be your responsibility to ensure that such disclosure to us is permitted by the Privacy Act (including by obtaining any appropriate consents).',
        ],
      },
      { type: 'p', text: '6.6 If you do not provide us with your personal information that we request, we may not be able to provide our Services to you.' },
      { type: 'p', text: '6.7 You hereby authorise us to disclose personal information about you to others (both within and outside of the Company) as we reasonably consider necessary to provide our Services to you. The types of bodies to whom we may disclose your personal information include but are not limited to photographers, media production providers, couriers and printing services. You also consent and authorise us to disclose your personal information to our contractors solicitors, accountants and our other advisors.' },
    ],
  },
  {
    title: '7. Confidentiality',
    body: [
      { type: 'p', text: '7.1 We undertake not to disclose or misuse your Confidential Information and personal information, subject only to applicable law and our professional and ethical obligations.' },
      { type: 'sub', text: 'Disclosure to Third Party Payers' },
      { type: 'p', text: '7.2 We may disclose to any Third Party Payer any information that it requires relating to the Costs.' },
      { type: 'sub', text: 'Citing our experience' },
      { type: 'p', text: '7.3 Subject to the professional and ethical obligations of confidentiality that we owe to you, we may cite the performance of the Services to other clients as an indication of our experience.' },
      { type: 'p', text: '7.4 The Company may use any deliverables, work, products and services created, made or delivered under this Agreement for promotional purposes, including showing such deliverables, work, products and services to any of the Company’s prospective clients, provided that such usage will not:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'cause the Company to breach its obligations under the Privacy Act;',
          'disclose the Client’s Confidential Information; and',
          'in the Company’s reasonable opinion, be detrimental to the Client’s interests.',
        ],
      },
    ],
  },
  {
    title: '8. Intellectual Property and Working Files',
    body: [
      { type: 'p', text: '8.1 Unless expressly agreed otherwise in writing between the Company and the Client:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'all Relevant IP and Working Files will be owned exclusively by, and vest exclusively in, the Company; and',
          'you must not use or reproduce any Relevant IP, or any other Intellectual Property Rights of the Company, or any of the Company’s customers, clients or suppliers without the Company’s prior written approval, other than for the purposes of completing the transactions that are contemplated in connection with this Agreement and to which the Services relate.',
        ],
      },
      { type: 'p', text: '8.2 You hereby assign, transfer and convey to the Company all current and future right, title and interest in all Relevant IP and acknowledge that all future Relevant IP will vest in the Company on and from creation.' },
      { type: 'p', text: '8.3 You must do anything necessary, including executing any documents, for the purpose of effecting, perfecting and/or protecting the Company’s title to any Relevant IP, in Australia or in such other countries as the Company may require at its discretion.' },
      { type: 'p', text: '8.4 You hereby consent to the doing of any acts, or making of any omissions, by the Company or any of the Company’s employees, officers, contractors, agents, licensees or assigns that infringes its Moral Rights in any Works that constitute Relevant IP, including:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'not naming you as the author of a Work; or',
          'amending or modifying (whether by changing, adding to or deleting/removing) any part of a Work but only if you are not named as the author of the amended or modified Work,',
        ],
      },
      { type: 'p', text: 'whether those acts or omissions occur before, on or after the date of this Agreement. You acknowledge that your consent pursuant to this clause is genuinely given without duress of any kind and that it has been given the opportunity to seek legal advice on the effect of giving that consent.' },
      { type: 'p', text: '8.5 You must not use the Company name or logo on any website or in any public statement without obtaining our prior written consent.' },
      { type: 'p', text: '8.6 The Company, in its absolute discretion may, upon request from the Client, provide copy of or access to the Company’s Working Files and on such terms and conditions as the Company deems fit in its absolute discretion.' },
    ],
  },
  {
    title: '9. Costs',
    body: [
      { type: 'sub', text: 'Our Professional Fees' },
      { type: 'p', text: '9.1 Based on our understanding of the scope of the Services as at the date of this Agreement, our monthly Fees for the Services are outlined in the Proposal, or our Fees for the Services are outlined in the Quote attached to this Agreement, whichever is applicable.' },
      { type: 'p', text: '9.2 You must pay our Fees in advance. The Company will invoice the Client for all relevant Costs:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'prior to the commencement of each monthly cycle of the Services outlined in the Proposal; and',
          'prior to the commencement of any Services outlined in the Quote attached to this Agreement;',
        ],
      },
      { type: 'p', text: '9.3 You must pay any tax invoice we issued pursuant to Clause 9.2 of this Agreement on or before the due date specified in the tax invoice.' },
      { type: 'sub', text: 'Hourly rates' },
      { type: 'p', text: '9.4 Our Fees do not include any Out-of-Scope Services. We may also charge additional fees if any of the factors set out below arises:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'The extent to which you give us your timely cooperation in accordance with clause 3.6 of our engagement terms.',
          'The extent to which the Services proceed in an orderly manner, including whether there is any delay or suspension of the Services and/or any need for the renegotiation or revision of the terms of this Agreement.',
          'Any variations in your instructions and/or the scope of the Services during the course of our engagement, and the extent to which any advice or documentation needs to be revised in light of any such variations.',
          'The number and duration of meetings, telephone calls and other communications with you and other entities and advisors involved in the provision of the Services.',
          'The level of co-operation that we receive from any such other entities and/or advisers, and the extent to which they may act unreasonably.',
          'Any changes in the law or circumstances during the course of our engagement.',
          'The level of complexity and/or unexpected issues that may arise.',
          'If the Services continues for a lengthy period of time, any revisions to our hourly rates that may occur during the course of the Services.',
          'Any force majeure event as contemplated by clause 11.8 of this Agreement.',
        ],
      },
      { type: 'p', text: '9.5 Our Fees in such circumstances will be calculated on the basis of the time spent by us in providing the Services at our Standard Hourly Rates.' },
      { type: 'p', text: '9.6 Hourly rates are proportionately charged for work involving periods of less than one hour. Our charges are structured in 6-minute units, with 10 units per hour – e.g., the time charged for an attendance of up to 6 minutes will be 1 unit and the time charged for an attendance between 6 and 12 minutes will be 2 units.' },
      { type: 'p', text: '9.7 We revise our Standard Hourly Rates periodically. The hourly rates set out in this Terms and Conditions will remain in force until the next time our Standard Hourly Rates are revised.' },
      { type: 'p', text: '9.8 If, at any time, we consider that additional Costs are likely (including as a result of any change to the scope of the Services that may be agreed in writing between the parties pursuant to clause 3.2), we will provide you with an estimate of such additional Costs in writing and, if you continue to give us instructions, you will be deemed to have accepted our estimate.' },
      { type: 'p', text: '9.9 You must pay any additional Costs you are deemed to have accepted pursuant to Clause 9.8 in advance (the Additional Costs). The Company will invoice the Client for the Additional Costs as soon as practicable after the Client’s deemed acceptance of our estimate under Clause 9.8 and prior to commencing any additional work and/or Out-of-Scope Services covered under the Additional Costs.' },
      { type: 'p', text: '9.10 You must pay any tax invoice we issued pursuant to Clause 9.9 of this Agreement on or before the due date specified in the tax invoice.' },
      { type: 'sub', text: 'Disbursements' },
      { type: 'p', text: '9.11 Our Fees do not include Disbursements such as courier services fees, costs of printed proofs, costs of photography and costs of media productions, which you will be required to pay in addition to our Fees.' },
      { type: 'p', text: '9.12 You hereby authorise the Company to obtain from third parties all products and services that the Company deems necessary in its absolute discretion in order to complete the Services and to incur Disbursements on your behalf for such products and services.' },
      { type: 'p', text: '9.13 Once we have paid a Disbursement on your behalf, you must reimburse us for it immediately upon demand by us, unless we elect in our absolute discretion to incorporate it into an invoice together with any Fees, in which case you will be required to pay for that Disbursement in accordance with the payment terms applicable to the invoice.' },
      { type: 'p', text: '9.14 If it becomes necessary to incur any Third Party Fees that we consider to be significant or unusual, estimates of those Third Party Fees will be provided to you and we will obtain your approval before incurring any such Third Party Fees.' },
      { type: 'p', text: '9.15 We reserve the right to:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'not incur or pay any particular Disbursement on your behalf; and/or',
          'forward the invoice for any Disbursement to you, in which case you will be responsible for payment of the invoice in accordance with its terms directly to the applicable third party.',
        ],
      },
      { type: 'sub', text: 'Third Party Payers' },
      { type: 'p', text: '9.16 The Client acknowledges and agrees that, even if a Third Party Payer has agreed or undertaken, or agrees or undertakes, to pay all or any part of the Costs on behalf of the Client, the Client remains responsible for the payment of those Costs and hereby guarantees to the Company the full and punctual payment of those Costs.' },
    ],
  },
  {
    title: '10. Invoicing and Payments',
    body: [
      { type: 'sub', text: 'Invoicing and payment terms' },
      { type: 'p', text: '10.1 Unless stated otherwise in this Agreement, our Costs will be invoiced at such times as we see fit in our discretion.' },
      { type: 'p', text: '10.2 You will be taken to have received each invoice in accordance with the provisions regarding receipt of notices in clause 14.' },
      { type: 'p', text: '10.3 Unless stated otherwise in this Agreement, you must pay the Costs that are the subject of any invoice rendered under this Agreement within 14 days after the date of issue of the relevant invoice.' },
      { type: 'p', text: '10.4 If you dispute part of an invoice, you must still pay the undisputed part as and when it is or becomes due and payable.' },
      { type: 'p', text: '10.5 The Company retains ownership of all deliverables and/or work provided under this Agreement until payment in full of all of our outstanding invoices.' },
      { type: 'p', text: '10.6 The Company may at its absolute discretion withhold, delay or refuse to provide any deliverables and/or work under this Agreement, including providing access to any accounts, platforms, websites, social media accounts and any usernames and passwords to the Client until payment in full of all of our outstanding invoices.' },
      { type: 'p', text: '10.7 Notwithstanding the retention of ownership under Clause 10.5 of this Agreement, the risk in the deliverables shall pass to the Client upon delivery. The Client agrees to insure the deliverables (if such deliverables are insurable) from the time of the delivery until the ownership passes to the Client.' },
      { type: 'sub', text: 'Suspension of Services' },
      { type: 'p', text: '10.8 We may at any time suspend all work for you until payment in full of all of our outstanding invoices.' },
      { type: 'sub', text: 'Method of payment' },
      { type: 'p', text: '10.9 All amounts to be paid by a party to another party under or in connection with this Agreement must be paid by way of electronic funds transfer into the account nominated by the other party.' },
      { type: 'sub', text: 'Recovery from third parties' },
      { type: 'p', text: '10.10 You must pay all Costs in a timely manner, regardless of whether or not you have a right of indemnity, recovery or reimbursement from a third party or any payment due to you by a third party is delayed or not received.' },
      { type: 'sub', text: 'No set-off or deduction' },
      { type: 'p', text: '10.11 All amounts payable under or in connection with this Agreement must be paid without set-off, counterclaim, withholding, deduction or claim to a lien whatsoever, whether or not any such set-off, counterclaim, withholding, deduction or lien arises under this Agreement (unless otherwise required by law).' },
      { type: 'p', text: '10.12 If a party is required by law to make a deduction or withholding in respect of any sum payable under or in connection with this Agreement to another party, it must, at the same time as the sum that is the subject of the deduction or withholding is payable, make a payment to the other party of such additional amount as is required to ensure that the net amount received by the other party will equal the full amount that would have been received by it had no such deduction or withholding been required to be made.' },
      { type: 'p', text: '10.14 If a liability of a party to another party under this Agreement becomes merged in a judgement or order and the interest rate that applies under that judgement or order is lower than the Default Rate, that party must, as an independent obligation, pay to the other party, at the same time and in the same manner as the sum that is the subject of that judgement or order is to be paid, such additional interest on that sum as is required to ensure that the total amount of interest that the other party receives in respect of that liability is equal to the Default Rate.' },
    ],
  },
  {
    title: '11. Liability and Obligations',
    body: [
      { type: 'p', text: '11.1 The Company will use reasonable skill and care in providing the Services.' },
      { type: 'sub', text: 'Indemnity and Release' },
      { type: 'p', text: '11.2 The Client irrevocably indemnifies, releases and covenants to hold the Company harmless from and against all Claims and Losses that may be suffered by, taken or made against the Company which arise in connection with:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'the proper performance or the Company’s exercise of any of its powers, duties or authorities under this Agreement unless such Claims or Losses are caused by the Company’s default, unlawful or negligent act or omission;',
          'any breach of this Agreement by the Client and/or any negligent or other tortious and/or unlawful conduct of the Client and/or unintended and/or misuse of the Services by the Client.',
        ],
      },
      { type: 'p', text: '11.3 To the maximum extent permitted by law, we will be liable only for the proportion of the Claims or Losses which our acts and omissions bear in relation to the total conduct of all persons causing or contributing to that Claims or Losses.' },
      { type: 'p', text: '11.4 Each indemnity contained in this Agreement is an additional, separate, independent and continuing obligation that survives the termination of this Agreement despite any settlement of account or other occurrence and remains in full force and effect until all money owing, contingently or otherwise, under the relevant indemnity has been paid in full and no one indemnity limits the generality of any other indemnity.' },
      { type: 'sub', text: 'Limitation of liability' },
      { type: 'p', text: '11.5 To the maximum extent permitted by law:' },
      {
        type: 'list',
        ordered: false,
        items: [
          '(Liability Cap) the aggregate liability of the Company, together with its Related Entities and its and their Representatives, for any Losses arising directly or indirectly out of, or in connection with, the Services (including the use by you or any other person of any deliverable under this Agreement) is capped at the value of the Fees that become payable under this Agreement (the Liability Cap);',
          '(Disclaimer of warranties) the Company, its Related Entities and its and their Representatives exclude all warranties, conditions and guarantees of any nature in respect of the Services and/or the economic, financial or other results that you may experience as a result of the provision of the Services, and limit their liability for breach of any non-excludable warranty, condition or guarantee that is implied by virtue of any Legislation to the supply of the Services again or the payment of the cost of having the Services supplied again (the choice of which is to be at the Company’s sole discretion); and',
          '(Exclusion of Consequential Loss) the Company and its Related Entities and its and their Representatives exclude all liability to you or any other person for any Consequential Loss arising directly or indirectly out of, or in connection with, the Services (including the use by you or any other person of any deliverable under this Agreement), even if the Company has been advised of the possibility of such Consequential Loss,',
        ],
      },
      { type: 'p', text: 'and the Client acknowledges and agrees that the Company holds the benefit of this Agreement, including this clause 11.5, on its own behalf and as agent and trustee for and on behalf of its Related Entities and its and their Representatives, and each of them is entitled to enforce this Agreement as it were a party to this Agreement.' },
      { type: 'sub', text: 'Liability in relation to Third Party Service Providers' },
      { type: 'p', text: '11.6 We will take reasonable care in providing instructions to any Third Party Service Providers but, to the maximum extent permitted by law, we take no responsibility for their work or how they carry out their instructions. In suggesting or selecting any Third Party Service Providers, we will rely on information that we are given as to their qualifications and experience but take no responsibility for such selections and give no warranty as to the ability of any Third Party Service Providers to appropriately carry out their work or as to the quality of their services.' },
      { type: 'sub', text: 'Apportionment of liability' },
      { type: 'p', text: '11.7 If you make any Claim against us for any Loss arising out of, or in connection with, the Services or this Agreement and some or all of that Loss was due to, or contributed to by your own acts or omissions or the acts or omissions of other persons for whose conduct you are responsible, or the acts or omissions of one or more other persons, not being partners, employees or agents of the Company for whose conduct we are responsible, then, to the maximum extent permitted by law, we will be liable only for that proportion of the Loss which our acts and omissions bear in relation to the total conduct of all persons causing or contributing to that Loss.' },
      { type: 'sub', text: 'Force majeure' },
      { type: 'p', text: '11.8 A party will not be liable for any delay or failure to perform its obligations (excluding payment obligations) under this Agreement to the extent that any such delay or failure arises from causes beyond its control, including fire, floods, acts of god, acts or regulations of any Governmental Agency, war, riot, terrorist activities, strikes, lockouts and industrial disputes.' },
      { type: 'sub', text: 'Destruction of documents' },
      { type: 'p', text: '11.9 Except in respect of any original executed documents that we have agreed in writing to retain on your behalf, you hereby consent to our destroying any documents that belong to you and which have been filed amongst our own papers after they are more than seven years old, or at any time provided that, if we destroy any hard copy document before it is seven years old, we will create an electronic copy of it before destroying it.' },
      { type: 'sub', text: 'Deletion of electronic files' },
      { type: 'p', text: '11.10 You hereby consent to our deleting any electronic documents that we have amongst our files (including any created pursuant to clause 11.9(b)) after the earlier of seven years from the creation of the electronic document, and completion or termination of our engagement in the Agreement.' },
      { type: 'sub', text: 'Access to documents' },
      { type: 'p', text: '11.11 If you request any documents from your file after they have been placed into storage, we reserve the right to charge you a reasonable fee for their retrieval.' },
      { type: 'p', text: '11.12 Where we hold documents in electronic form (including any created pursuant to clause 11.9(b)) and you are entitled to a copy of them, those copies will be provided to you in electronic form and not printed.' },
      { type: 'sub', text: 'Non-Disparagement' },
      { type: 'p', text: '11.13 Subject to clause 11.14, on and from the date of this Agreement, each party must not:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'make, express, transmit, speak, write, verbalise or otherwise communicate in any way (directly or indirectly, in any capacity or manner) any remark, comment, message, information, declaration, communication or other statement of any kind (whether verbal, in writing, electronically transferred or otherwise) that might reasonably be construed to be critical of, or derogatory or negative towards, any other party or any Representative of any other party; or',
          'cause, further, assist, solicit, encourage or knowingly permit any other person to do so, or support or participate in any other person doing so, and must take all reasonable steps to prevent its Representatives from doing so.',
        ],
      },
      { type: 'p', text: '11.14 Clause 11.13 shall not prohibit any party from making any statement or disclosure as required by law or court order, provided that such party must promptly notify the other party in writing in advance of any such statement or disclosure, if reasonably practicable, and reasonably assist the other party in obtaining confidential treatment for, or avoiding or minimising the dissemination of, such statement or disclosure to the extent reasonably requested by any party.' },
    ],
  },
  {
    title: '12. Commencement, Duration and Termination',
    body: [
      { type: 'p', text: '12.1 This Agreement shall commence on the Commencement Date and shall continue indefinitely until it is terminated in accordance with this Agreement.' },
      { type: 'sub', text: 'Termination with notice' },
      { type: 'p', text: '12.2 The Client may, without limitation to its rights under clause 12.5, terminate this Agreement at any time by giving at least 90 days’ notice to the Company.' },
      { type: 'p', text: '12.3 The Company may, without limitation to its rights under clause 12.5, terminate this Agreement at any time by giving at least 90 days’ notice to the Client.' },
      { type: 'p', text: '12.4 To remove doubt, the termination of this Agreement pursuant to Clauses 12.2 or 12.3 shall take effect on the day immediately following the expiration of the notice period under those Clauses (the date of termination).' },
      { type: 'sub', text: 'Termination for Breach' },
      { type: 'p', text: '12.5 Each party may terminate this Agreement immediately by notice to the other party if an Event of Default occurs in respect of the other party.' },
      { type: 'p', text: '12.6 If a party commits any material or persistent breach of this Agreement (the Defaulting Party), the other party may (but is not obliged to) provide the Defaulting Party with a notice of breach in writing. If the Defaulting Party fails to remedy the breach within 20 Business Days, or such other period as agreed, after the date of its receipt of such notice, the other party may terminate this Agreement with immediate effect upon providing the Defaulting Party with a further notice of termination in writing.' },
      { type: 'sub', text: 'Effect of Termination' },
      { type: 'p', text: '12.7 In the event of any termination of this Agreement in any circumstances and for any reason whatsoever:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'the Client will remain liable to pay all Costs accrued up to and including the date of termination, whether or not invoiced prior to the date of termination; and',
          'the Company will send to the Client a final invoice for the balance of any unbilled Costs accrued up to and including the date of termination and clause 10 will apply in respect thereof.',
        ],
      },
      { type: 'sub', text: 'Partially completed deliverables' },
      { type: 'p', text: '12.7 Upon the cessation of the Company’s engagement under this Agreement, subject to payment of all outstanding Costs by the Client in accordance with the terms of this Agreement, the Company will deliver to the Client any and all partially completed deliverables that are included within the scope of the Services.' },
      { type: 'sub', text: 'Accrued rights and obligations' },
      { type: 'p', text: '12.8 Termination of this Agreement will not affect any rights or obligations that the parties have accrued under it prior to such termination.' },
      { type: 'sub', text: 'Survival' },
      { type: 'p', text: '12.9 Provisions of this Agreement that, expressly or by implication, are intended to survive its termination will survive and continue to bind the parties.' },
    ],
  },
  {
    title: '13. GST',
    body: [
      { type: 'sub', text: 'Definitions regarding GST' },
      { type: 'p', text: '13.1 In this clause 13:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'expressions that are not defined, but which have a defined meaning in the GST Law, have the same meaning as in the GST Law;',
          'any part of a supply that is treated as a separate supply for GST purposes (including attributing GST payable to tax periods) will be treated as a separate supply for the purposes of this clause 13; and',
          'any consideration that is specified to be inclusive of GST must not be taken into account in calculating the GST payable in relation to a supply for the purpose of this clause 13.',
        ],
      },
      { type: 'sub', text: 'Consideration is exclusive of GST' },
      { type: 'p', text: '13.2 Unless expressly indicated otherwise, any sum payable, or amount used in the calculation of a sum payable, under this Agreement has been determined without regard to GST and must be increased on account of any GST payable in accordance with this clause 13.' },
      { type: 'sub', text: 'Receiving Party to pay additional amount' },
      { type: 'p', text: '13.3 If we have assessed that no GST is payable in respect of our Fees and subsequently we change our assessment or the Australian Taxation Office assesses that GST is payable, then GST will be added to, and form part of, our Fees at the prevailing GST rate, and we reserve the right to recover any such GST from you.' },
      { type: 'p', text: '13.4 If GST is imposed on any supply made under or in accordance with this Agreement, the recipient of the supply (Receiving Party) must pay to the supplier (Supplier) an additional amount equal to the GST payable on the supply, subject to the Receiving Party receiving a valid tax invoice, or a document that the Commissioner will treat as a tax invoice, in respect of the supply at or before the time of payment. Payment of the additional amount will be made at the same time and in the same manner as payment for the supply is required to be made in accordance with this Agreement.' },
      { type: 'sub', text: 'GST on Disbursements' },
      { type: 'p', text: '13.5 For the purposes of the GST Law, you (and not the Company) will acquire the goods and services that constitute the Disbursements. You may therefore be entitled to an input tax credit for any GST included in any Disbursements, to the extent that you satisfy the requirements of the GST Law. We will supply you with details of the amounts invoiced by the relevant third parties and will retain the original tax invoices on your behalf. Whether or not such third parties should add GST on the amounts they charge for Disbursements provided on your behalf is a matter between you and those third parties. Where such a third party includes an amount on account of GST that we pay on your behalf, you must repay us the whole amount paid by us, including the GST component.' },
      { type: 'sub', text: 'Fines, penalties and interest' },
      { type: 'p', text: '13.6 The amount recoverable on account of GST under this clause 13 by the Supplier will include any fines, penalties, interest and other charges incurred as a consequence of any late payment or other default by the Receiving Party under this clause 13.' },
      { type: 'sub', text: 'Reimbursement' },
      { type: 'p', text: '13.7 If any party is required to pay, reimburse or indemnify another party for the whole or any part of any cost, expense, loss, liability or other amount that the other party has incurred or will incur in connection with this Agreement, the amount must be reduced by the amount for which the other party can claim an input tax credit, partial input tax credit or other similar offset.' },
      { type: 'sub', text: 'Adjustment events' },
      { type: 'p', text: '13.8 If, at any time, an adjustment event arises in respect of any supply made by a party under this Agreement, a corresponding adjustment must be made between the parties in respect of any amount paid to the Supplier by the Receiving Party pursuant to clause 13.3 and payments to give effect to the adjustment must be made and the Supplier must issue an adjustment note.' },
    ],
  },
  {
    title: '14. Notices',
    body: [
      { type: 'p', text: '14.1 A notice given to a party under this Agreement must be:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'in writing in English;',
          'sent to the address, fax number or email address of the relevant party as set out in the covering engagement letter (or such other address, fax number or email address as the relevant party may notify to the other parties from time to time); and',
          {
            text: 'delivered/sent either:',
            sublist: {
              ordered: true,
              items: [
                'personally;',
                'by commercial courier;',
                'by pre-paid post;',
                'if the notice is to be served by post outside the country from which it is sent, by airmail;',
                'by fax; or',
                'by e-mail.',
              ],
            },
          },
        ],
      },
      { type: 'p', text: '14.2 A notice is deemed to have been received:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'if delivered personally, at the time of delivery;',
          'if delivered by commercial courier, at the time of signature of the courier’s receipt;',
          'if sent by pre-paid post, 48 hours from the date of posting;',
          'if sent by airmail, five days after the date of posting;',
          'if sent by fax, at the time shown in the transmission report generated by the machine from which the fax was sent; or',
          'if sent by e-mail, 4 hours after the sent time (as recorded on the sender’s e-mail server), unless the sender receives a notice from the Company’s email server or internet service provider that the message has not been delivered to the Company, except that, if such deemed receipt is not within business hours (meaning 9:00 am to 5:30 pm on a Business Day), the notice will be deemed to have been received at the next commencement of business hours in the place of deemed receipt.',
        ],
      },
      { type: 'p', text: '14.3 To prove service, it is sufficient to prove that:' },
      {
        type: 'list',
        ordered: false,
        items: [
          'in the case of post – that the envelope containing the notice was properly addressed and posted;',
          'in the case of fax – the notice was transmitted to the fax number of the party; and',
          'in the case of email – the email was transmitted to the Company’s email server or internet service provider.',
        ],
      },
    ],
  },
  {
    title: '15. General',
    body: [
      { type: 'sub', text: 'Costs' },
      { type: 'p', text: '15.1 All costs and expenses in connection with the negotiation, preparation and execution of this Agreement will be borne the party that incurred the costs.' },
      { type: 'p', text: '15.2 The Client shall, on indemnity basis, be liable for the Company’s costs and expenses in connection with any Event of Default by the Client.' },
      { type: 'sub', text: 'Further assurances' },
      { type: 'p', text: '15.3 Each party must (at its own expense) promptly execute and deliver all such documents, and do all such things, as any other party may from time to time reasonably require for the purpose of giving full effect to the provisions of this Agreement.' },
      { type: 'sub', text: 'Entire agreement' },
      { type: 'p', text: '15.4 This Agreement contains the entire understanding between the parties in relation to its subject matter and supersedes any previous arrangement, understanding or agreement relating to its subject matter. There are no express or implied conditions, warranties, promises, representations or obligations, written or verbal, in relation to this Agreement other than those expressly stated in it or necessarily implied by statute.' },
      { type: 'sub', text: 'Severability' },
      { type: 'p', text: '15.5 If a provision of this Agreement is invalid or unenforceable in a jurisdiction, it is to be read down or severed in that jurisdiction to the extent of the invalidity or unenforceability, and that fact does not affect the validity or enforceability of that provision in another jurisdiction, or the remaining provisions.' },
      { type: 'sub', text: 'No waiver' },
      { type: 'p', text: '15.6 No failure, delay, relaxation or indulgence by a party in exercising any power or right conferred upon it under this Agreement will operate as a waiver of that power or right. No single or partial exercise of any power or right precludes any other or future exercise of it, or the exercise of any other power or right under this Agreement.' },
      { type: 'sub', text: 'Amendment' },
      { type: 'p', text: '15.7 This Agreement may not be varied except by written instrument executed by all of the parties.' },
      { type: 'sub', text: 'Assignment' },
      { type: 'p', text: '15.8 A party must not assign, transfer, sub-contract, create any trust over or otherwise deal in any way with any of its rights or obligations under this Agreement without the prior written consent of each other party.' },
      { type: 'sub', text: 'Counterparts' },
      { type: 'p', text: '15.9 This Agreement may be executed in any number of counterparts, each of which is an original and which together will have the same effect as if each party had signed the same document.' },
      { type: 'sub', text: 'Electronic exchange' },
      { type: 'p', text: '15.10 Delivery of an executed counterpart of this Agreement by facsimile, or by email in PDF or other image format, or using an online platform will be equally effective as delivery of an original signed hard copy of that counterpart.' },
      { type: 'p', text: '15.11 The Client hereby confirms that they have received a copy of this Agreement.' },
      { type: 'sub', text: 'Governing law and jurisdiction' },
      { type: 'p', text: '15.12 This Agreement and any disputes or claims arising out of or in connection with its subject matter or formation (including non-contractual disputes or claims) are governed by, and shall be construed in accordance with, the laws of New South Wales, Australia.' },
      { type: 'p', text: '15.13 The parties irrevocably agree that the courts of New South Wales, Australia have exclusive jurisdiction to settle any dispute or claim that arises out of, or in connection with, this Agreement or its subject matter or formation (including non-contractual disputes or claims).' },
    ],
  },
]
